config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'

  resources :items, only: [:index] do
    member do
     post  :add_to_cart
     post  :remove_from_cart
    end
  end

  resource :cart, only: [:show] do
    resources :promotion_codes, only: [:index, :create, :destroy]
  end

  resources :orders, only: [:new, :create, :show] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :carts_items, inverse_of: :cart
  has_many :items, through: :carts_items
  has_many :carts_promotion_codes, inverse_of: :cart
  has_many :promotion_codes, through: :carts_promotion_codes

  def add_item item
    cart_item = self.carts_items.find_or_initialize_by(item: item)
    cart_item.increase_count
    cart_item.save
  end

  def remove_item item
    if cart_item = carts_items.find_by(item: item)
    cart_item.decrease_count
    cart_item.save
    end
  end

  def total
    total_with_promotion_codes
  end

  def items_total
    @items_total_price ||= get_items_total
  end

  def get_items_total
    carts_items.inject(0) do |items_price, item|
      items_price += item.price
    end
  end

  def total_with_promotion_codes
    promotion_codes.inject(items_total) do |discounted_total, code|
      code.perform(discounted_total)
    end.round(2)
  end

  def clear
    carts_items.delete_all
    carts_promotion_codes.delete_all
  end
end

app/models/carts_item.rb
class CartsItem < ApplicationRecord

  belongs_to :cart, inverse_of: :carts_items
  belongs_to :item
  before_save :destroy_if_count_0

  delegate :name, to: :item

  def increase_count
    self.count += 1
  end

  def decrease_count
    self.count -= 1
  end

  def price
    calculate_item_price.round(2)
  end

  private

  def calculate_item_price
    item.item_promotion.present? ? item.item_promotion.perform(self.count) : item.price * self.count
  end

  def destroy_if_count_0
    destroy if count <= 0
  end

end

app/models/carts_promotion_code.rb
class CartsPromotionCode < ApplicationRecord

  belongs_to :cart, inverse_of: :carts_promotion_codes
  belongs_to :promotion_code

  validates_uniqueness_of :promotion_code_id, scope: :cart_id
  validates_associated :cart
  validates_uniqueness_of :cart_id, if: :solo_promotion_code?
  validate :no_other_solo

  def solo_promotion_code?
    promotion_code.solo?
  end

  def no_other_solo
    errors.add(:promotion_code, 'already a solo promotion') if cart.promotion_codes.where(solo: true).present?
  end
end

app/models/code_types/amount_off.rb
module CodeTypes
  class AmountOff < Base
    def promote_price price
      price - parameter
    end
  end
end

app/models/code_types/base.rb
module CodeTypes
  class Base
    attr_reader :parameter
    def initialize parameter
      @parameter = parameter
    end
    
    def perform old_price
      new_price = promote_price old_price
      new_price <= 0 ? 0 : new_price
    end
  end
end

app/models/code_types/percentage_off.rb
module CodeTypes
  class PercentageOff < Base
    def promote_price price
      price * (1 - parameter)
    end
  end
end

app/models/concerns/updates_cart.rb
module UpdatesCart
  extend ActiveSupport::Concern
  included do
    after_commit :update_cart_total
  end

  def update_cart_total
    cart.update_total
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :carts_items
  has_many :carts, through: :carts_items
  has_one :item_promotion
  has_many :orders_items, inverse_of: :item
  has_many :orders, through: :orders_items
  validates :name, :price, presence: true
end

app/models/item_promotion.rb
class ItemPromotion < ApplicationRecord
  belongs_to :item
  validates :quantity, :price, :item, presence: true

  def perform count
    promotion_price count
  end

  def promotion_price count
    (promoted, remain) = count.divmod(quantity)
    price * promoted + item.price * remain
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_items, inverse_of: :order
  has_many :items, through: :orders_items
  has_many :orders_promotion_codes, inverse_of: :order
  has_many :promotion_codes, through: :orders_promotion_codes
  belongs_to :cart

  validates :email, :address, :credit_card, presence: true
  validate :check_cart_version

  attr_accessor :cart_version

  def self.from_cart cart
    new.tap do |order|
      order.cart = cart
      order.total = cart.total

      cart.carts_items.each do |item|
        order.orders_items.build(count: item.count, price: item.price, item_id: item.item_id)
      end

      cart.promotion_codes.each do |promotion_code|
        order.orders_promotion_codes.build(promotion_code_id: promotion_code.id)
      end
    end
  end

  def check_cart_version
    cart_version == cart
  end
end

app/models/orders_item.rb
class OrdersItem < ApplicationRecord
  belongs_to :order, inverse_of: :orders_items
  belongs_to :item

  delegate :name, to: :item
end

app/models/orders_promotion_code.rb
class OrdersPromotionCode < ApplicationRecord

  belongs_to :order, inverse_of: :orders_promotion_codes
  belongs_to :promotion_code
end

app/models/promotion_code.rb
class PromotionCode < ApplicationRecord
  CODE_TYPES = {
    'percentage_off' => CodeTypes::PercentageOff,
    'amount_off' => CodeTypes::AmountOff,
  }

  has_many :carts_promotion_codes
  has_many :carts, through: :carts_promotion_codes
  has_many :orders_promotion_codes
  has_many :orders, through: :orders_promotion_codes

  validates :name, :parameter, presence: true
  validate :valid_code_type?

  def perform value
    CODE_TYPES[code_type].new(parameter).perform value
  end

  private
  def valid_code_type?
    CODE_TYPES.include?(code_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  after_action :set_current_cart
  helper_method :current_cart
  protect_from_forgery with: :exception

  private

  def current_cart
    Cart.find_or_create_by(id: session[:cart])
  end

  def set_current_cart
    session[:cart] = current_cart.id
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def add_to_cart
    current_cart.add_item(item)
    redirect_to cart_path
  end

  def remove_from_cart
    current_cart.remove_item(item)
    redirect_to cart_path
  end

  private

  def item
    @item ||= Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @cart = current_cart
  end

  def create
    @order = Order.from_cart(current_cart)
    @order.assign_attributes(order_params)

    if @order.save
      current_cart.clear
      redirect_to @order
    else
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:email, :address, :credit_card, :cart_version)
  end
end

app/controllers/promotion_codes_controller.rb
class PromotionCodesController < ApplicationController
  def create
    @promotion_code = PromotionCode.find_by(name: params[:name])

    current_cart.carts_promotion_codes.find_or_create_by(promotion_code: @promotion_code).save

    redirect_to cart_path
  end

  def destroy
    current_cart.promotion_codes.destroy(promotion_code)
    redirect_to cart_path
  end

  private

  def promotion_code
    @promotion_code ||= PromotionCode.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<ul><%= render @cart.carts_items  %> </ul>

<h2>Total: <span class="total"><%= @cart.total %></span></h2>

<%= render 'promotion_codes/form' %>

<ul class="promotion-codes"><%= render @cart.promotion_codes %></ul>

<%= link_to 'Return to shop', items_path, class: 'return-to-shop' %>
<%= link_to 'Checkout', new_order_path, class: 'checkout' %>

app/views/carts_items/_carts_item.html.erb
<li class="item">
  <span class="count"><%= carts_item.count %></span>
  <span class="name"><%= carts_item.name %></span>
  <span class="price"><%= carts_item.price %></span>
  <%= link_to 'Remove from Cart', remove_from_cart_item_path(carts_item.item), method: :post, class: 'remove-from-cart' %>
</li>

app/views/items/_item.html.erb
<li class="item">
  <span class="name"><%= item.name %></span>
  <span class="price"><%= item.price %></span>
  <%= link_to 'Remove from Cart', remove_from_cart_item_path(item), method: :post, class: 'remove-from-cart' %>

app/views/items/index.html.erb
<ul>
  <% @items.each do |item| %>
    <li class="item">
      <span class="name"><%= item.name %></span>
      <span class="price"><%= item.price %></span>
      <%= link_to 'Add to Cart', add_to_cart_item_path(item), method: :post, class: 'add-to-cart' %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<ul><%= render @cart.items  %> </ul>

<ul><%= render @cart.promotion_codes %></ul>

<p>Total: <span class="total"><%= @cart.total %></span><p>

<%= form_for Order.new do |f|%>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :credit_card %>
  <%= f.text_field :credit_card %>

  <%= f.label :cart_update_time %>
  <%= f.hidden_field :cart_version, value: @cart.updated_at  %>

  <%= f.submit %>
<% end %>

<%= link_to 'Return to cart', cart_path, class: 'return-to-cart' %>

app/views/orders/show.html.erb
<ul><%= render @order.orders_items  %> </ul>

<ul><%= render partial: 'promotion_codes/order_promotion_code', collection: @order.promotion_codes, as: :code %></ul>

<p>Total: <span class="total"><%= @order.total %></span><p>
<%= link_to 'Return to Shop', items_path, class: 'return-to-shop' %>

app/views/orders_items/_orders_item.html.erb
<li class="item">
  <span class="count"><%= orders_item.count %></span>
  <span class="name"><%= orders_item.name %></span>
  <span class="price"><%= orders_item.price %></span>
</li>

app/views/promotion_codes/_form.html.erb
<%= form_tag cart_promotion_codes_path, method: :post, class: 'add-promotion-code' do %>
  <%= text_field_tag :name %>
  <%= submit_tag 'Add Promotion Code' %>
<% end %>

app/views/promotion_codes/_order_promotion_code.html.erb
<li class="promotion-code">
  <span class="name"><%= code.name %></span>
</li>

app/views/promotion_codes/_promotion_code.html.erb
<li class="promotion-code">
  <span class="name"><%= promotion_code.name %></span>
  <%= link_to 'Remove from Cart', cart_promotion_code_path(promotion_code), method: :delete, class: 'remove-code' %>
</li>